[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
money_expense = "8QYJS7akSyHJEoAg6LZ5oVCMxSGr6Dz9qFciwLz2mQRC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
